
---
title: "Explorando Dados do TCGA-BRCA com TCGAbiolinks"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Explorando Dados do TCGA-BRCA com TCGAbiolinks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introdução

Neste vignette, exploraremos o uso do pacote `TCGAbiolinks` para acessar e baixar dados de sequenciamento de RNA (RNA-Seq) do The Cancer Genome Atlas (TCGA) para o câncer de mama (BRCA).

O pacote `TCGAbiolinks` facilita o acesso a grandes conjuntos de dados genômicos, provendo uma ponte entre o portal de dados do Genomic Data Commons (GDC) e a análise bioinformática em R.

## Instalação e Carregamento de Pacotes

Inicialmente, instale e carregue os pacotes necessários para este vignette.

\```{r setup, message=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
BiocManager::install("TCGAbiolinks")
library(TCGAbiolinks)
library(SummarizedExperiment)
\```

## Configuração de Parâmetros de Consulta

Definimos três parâmetros principais para nossa consulta de dados:

- `data_type`: Tipo de dados de interesse (por exemplo, RNASeq).
- `expression_type`: Tipo de dados de expressão (por exemplo, contagem ou TPM).
- `cancer_type`: O tipo de câncer de interesse (por exemplo, TCGA-BRCA).

\```{r}
data_type <- "RNASeq"
expression_type <- "count"
cancer_type <- "TCGA-BRCA"
\```

## Consulta de Dados com GDCquery

A função `GDCquery` do pacote `TCGAbiolinks` permite que você faça consultas ao GDC, especificando o projeto (neste caso, "TCGA-BRCA") e categorias de dados.

\```{r}
projects <- GDCquery(project = cancer_type, 
                     data.category = data_type, 
                     data.type = expression_type)
\```

### Explicação da Função GDCquery

- `project`: Especifica o projeto do TCGA do qual queremos baixar dados.
- `data.category`: Especifica o tipo de dados que desejamos (por exemplo, "Transcriptome Profiling").
- `data.type`: Especifica o tipo de dados de expressão que desejamos (por exemplo, "Gene Expression Quantification").

## Download dos Dados

Após fazer a consulta com `GDCquery`, você pode baixar os dados para a sua máquina local utilizando a função `GDCdownload`.

\```{r}
query_download <- GDCquery(project = "TCGA-BRCA",
                           data.category = "Transcriptome Profiling",
                           data.type = "Gene Expression Quantification",
                           workflow.type = "HTSeq - Counts")
GDCdownload(query = query_download)
\```

## Considerações Finais

Este vignette fornece uma introdução básica sobre como utilizar o pacote `TCGAbiolinks` para baixar dados do TCGA. Explore a documentação do pacote e outros recursos para aprendizado para entender mais sobre as capacidades e funcionalidades avançadas disponíveis no `TCGAbiolinks`.

**Nota Importante:** Sempre esteja ciente e respeite as diretrizes éticas e legais ao trabalhar com dados genômicos e biológicos em suas pesquisas.

